---

- name: Send nginx configuration
  copy:
    src: nginx.conf
    dest: /home/devops/nginx.conf

- name: Createreate Nginx
  docker_container:
    name: nginx
    image: nginx
    state: present
    ports:
      - "3000:3000"
    volumes:
      - "/home/devops/nginx.conf:/etc/nginx/nginx.conf:ro"